function sketchesLoad(){
    varjsonObj = JSON.parse({"sketches": [
        {
                "visualID": "1241579",
                "title": "lissajouscurvegenerator",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-2304:42:58",
                "thumbnailUpdatedOn": "2021-08-1916:06:21",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "623",
                "numberOfHearts": "19",
                "numberOfComments": "0"
            },
            {
                "visualID": "1824592",
                "title": "BrineCleeper",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-1617:32:47",
                "thumbnailUpdatedOn": "2023-02-1018:10:56",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "25",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1353905",
                "title": "perlinnoise.txt",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-1007:05:13",
                "thumbnailUpdatedOn": "2022-01-0511:38:39",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "42",
                "numberOfHearts": "2",
                "numberOfComments": "0"
            },
            {
                "visualID": "1675719",
                "title": "newton'sfractal",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-1007:04:52",
                "thumbnailUpdatedOn": "2022-10-0818:38:36",
                "parentID": "1617720",
                "isTutorial": "0",
                "numberOfViews": "27",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1857987",
                "title": "worleynoisewithgradientdescent",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-1007:04:20",
                "thumbnailUpdatedOn": "2023-04-3007:52:58",
                "parentID": "1675694",
                "isTutorial": "0",
                "numberOfViews": "17",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1917131",
                "title": "ar[c\/t]",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-05-1007:02:53",
                "thumbnailUpdatedOn": "2023-05-0904:37:13",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "8",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1906316",
                "title": "springsimulation",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-04-2414:21:28",
                "thumbnailUpdatedOn": "2023-04-2414:32:30",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "46",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1828582",
                "title": "mazegeneration",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-2114:47:56",
                "thumbnailUpdatedOn": "2023-04-3008:01:53",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "28",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1865321",
                "title": "waveinterference",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-1418:41:54",
                "thumbnailUpdatedOn": "2023-03-1405:45:23",
                "parentID": "1636038",
                "isTutorial": "0",
                "numberOfViews": "26",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1565783",
                "title": "squarespiralv3",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0704:37:10",
                "thumbnailUpdatedOn": "2023-03-0306:45:30",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "19",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1241657",
                "title": "shapecollage",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0214:29:47",
                "thumbnailUpdatedOn": "2023-02-2512:07:52",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "55",
                "numberOfHearts": "1",
                "numberOfComments": "0"
            },
            {
                "visualID": "1294174",
                "title": "randomisedfractaltreegenerator",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0214:29:43",
                "thumbnailUpdatedOn": "2021-12-0306:14:49",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "94",
                "numberOfHearts": "4",
                "numberOfComments": "0"
            },
            {
                "visualID": "1505324",
                "title": "voronoi",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0214:29:07",
                "thumbnailUpdatedOn": "2022-03-0408:11:49",
                "parentID": "1504182",
                "isTutorial": "0",
                "numberOfViews": "112",
                "numberOfHearts": "2",
                "numberOfComments": "0"
            },
            {
                "visualID": "1691351",
                "title": "GPUnoise",
                "isPjs": "3",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0214:29:05",
                "thumbnailUpdatedOn": "2022-11-0716:05:27",
                "parentID": "1675694",
                "isTutorial": "0",
                "numberOfViews": "17",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1818603",
                "title": "wanderinglissajouscurves",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2023-03-0213:06:49",
                "thumbnailUpdatedOn": "2023-03-0213:25:34",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "8",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1617720",
                "title": "mandelbruh",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2022-07-2907:29:33",
                "thumbnailUpdatedOn": "2022-11-2605:21:16",
                "parentID": "1507398",
                "isTutorial": "0",
                "numberOfViews": "62",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1616096",
                "title": "Rings",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": "2022-07-2119:13:21",
                "thumbnailUpdatedOn": "2022-07-2116:28:37",
                "parentID": "1507398",
                "isTutorial": "0",
                "numberOfViews": "55",
                "numberOfHearts": "0",
                "numberOfComments": "2"
            },
            {
                "visualID": "1971917",
                "title": "BitChess2",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-07-1310:04:33",
                "parentID": "1815171",
                "isTutorial": "0",
                "numberOfViews": "5",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1968461",
                "title": "Borderboxstyleeditor",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-07-0707:27:56",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "3",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1967706",
                "title": "would",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-07-0517:25:56",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "5",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1957522",
                "title": "grap",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-06-1813:30:04",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "11",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1956086",
                "title": "gas",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-06-1511:57:04",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "8",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1935753",
                "title": "Djarikepas",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-05-2214:39:26",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "20",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1931642",
                "title": "harmony",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-05-1816:59:52",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "4",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1910207",
                "title": "website",
                "isPjs": "3",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-04-2607:25:17",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "10",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1894054",
                "title": "nebulousmandelsine",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-04-1112:43:32",
                "parentID": "1617720",
                "isTutorial": "0",
                "numberOfViews": "5",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1863190",
                "title": "altnoise",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-03-2010:40:32",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "4",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1845558",
                "title": "lgith",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-02-2313:36:13",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "6",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1837152",
                "title": "SaullingFans",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-02-2405:27:47",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "7",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1832529",
                "title": "Quickmaths",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-02-2010:12:33",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "20",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1829325",
                "title": "PasterWind",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-02-1006:11:41",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "4",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1821554",
                "title": "TextChat",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-02-0518:13:22",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "62",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1815171",
                "title": "BitChess",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-01-3009:26:52",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "37",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1780856",
                "title": "lorenzattractor",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-01-3115:50:13",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "28",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1751989",
                "title": "harmonicoscillation",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2023-03-0214:27:26",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "16",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1659683",
                "title": "old",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-09-2114:47:04",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "24",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1649877",
                "title": "uno[WIP]",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-09-1610:02:16",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "6",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1636063",
                "title": "Raymarching[WIP]",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-08-3119:33:39",
                "parentID": "1636038",
                "isTutorial": "0",
                "numberOfViews": "9",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1621037",
                "title": "Lines",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-07-2908:02:06",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "16",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1589346",
                "title": "webbing",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-06-1211:09:26",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "13",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1575593",
                "title": "shapespiral",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-05-1603:29:14",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "10",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1507398",
                "title": "GLSLblank",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-03-0708:37:13",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "12",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1506701",
                "title": "amplitude",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-03-1504:52:51",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "35",
                "numberOfHearts": "1",
                "numberOfComments": "0"
            },
            {
                "visualID": "1477417",
                "title": "fourierseries",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-02-2808:14:16",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "40",
                "numberOfHearts": "2",
                "numberOfComments": "0"
            },
            {
                "visualID": "1394047",
                "title": "classificationneuralnet",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2021-12-1107:47:41",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "14",
                "numberOfHearts": "1",
                "numberOfComments": "0"
            },
            {
                "visualID": "1377511",
                "title": "dynamicbasesystem(DBS)",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-01-1310:28:33",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "12",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            },
            {
                "visualID": "1374500",
                "title": "playfulcube",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2022-03-2908:17:35",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "17",
                "numberOfHearts": "0",
                "numberOfComments": "1"
            },
            {
                "visualID": "1340448",
                "title": "computingpiusinganinfintesum",
                "isPjs": "2",
                "active": "1",
                "isDraft": "0",
                "isPrivate": "0",
                "pinnedOn": null,
                "thumbnailUpdatedOn": "2021-11-1208:05:38",
                "parentID": null,
                "isTutorial": "0",
                "numberOfViews": "15",
                "numberOfHearts": "0",
                "numberOfComments": "0"
            }
        ]
    })
    let c = document.getElementById("sketchesContainer");
    for (let i = 0; i < jsonObj.sketches.length; i++) {
        let currentSketch = jsonObj.sketches[i];
        let newA = document.createElement("a");
        newA.setAttribute("href", "https://openprocessing.org/sketches/" + str(currentSketch.visualID));
        let newDiv = document.createElement("div");
        newDiv.setAttribute("class", "stdHalfCol");
        newDiv.setAttribute("innerText", currentSketch.title);
        newA.appendChild(newDiv);
        c.appendChild(newA);
    }
}